<?php

// Generated by ZF2's ./bin/classmap_generator.php

return array(
    'TwwDoctrineFreeTds\DBAL\Driver\PDOFreeTDS\Connection' => __DIR__ . '/../../src/TwwDoctrineFreeTds/DBAL/Driver/PDOFreeTDS/Connection.php',
    'TwwDoctrineFreeTds\DBAL\Driver\PDOFreeTDS\Driver'     => __DIR__ . '/../../src/TwwDoctrineFreeTds/DBAL/Driver/PDOFreeTDS/Driver.php',
    'TwwDoctrineFreeTds\Module'                            => __DIR__ . '/../../src/TwwDoctrineFreeTds/Module.php',
);
